**1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns**

In [1]:
import numpy as np
import random
arr= np.random.randint(1,100,size=(3,3))
arr

array([[67, 76, 27],
       [70, 46, 96],
       [84, 31, 24]])

In [5]:
arr.T  #converting rows to columns and columns to rows using transpose

array([[67, 70, 84],
       [76, 46, 31],
       [27, 96, 24]])

**2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

In [10]:
arr=np.arange(0,10) #uses NumPy's arange function to generate the 1D array
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr.reshape(2,5) ##the reshape method to reshape it into the desired shapes

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

**3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

In [16]:
arr=np.random.rand(4,4)
arr

array([[0.73776106, 0.29699147, 0.11230825, 0.53984815],
       [0.65470228, 0.07945106, 0.80271329, 0.08328346],
       [0.13076037, 0.12176792, 0.62120499, 0.39315941],
       [0.37621356, 0.23868736, 0.20958458, 0.59576243]])

In [22]:
arr1=np.pad(arr,pad_width=1, mode='constant', constant_values=0) #np.pad(): Pads the array. pad_width=1 adds a border of width 1 around the array, mode='constant' specifies that the padding should be with a constant value, and constant_values=0 sets the padding value to zero.

In [25]:
print(arr1)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.73776106 0.29699147 0.11230825 0.53984815 0.        ]
 [0.         0.65470228 0.07945106 0.80271329 0.08328346 0.        ]
 [0.         0.13076037 0.12176792 0.62120499 0.39315941 0.        ]
 [0.         0.37621356 0.23868736 0.20958458 0.59576243 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

In [3]:
import numpy as np
arr=np.arange(10,65,5) #np.arange(start, stop, step): Generates values starting from start to stop (but not including stop), with a given step size.
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

**5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.**

In [4]:
myarr = np.array(['python', 'numpy', 'pandas']) #given string array
myarr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [5]:
np.char.upper(myarr) #transform into uppercase

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [6]:
np.char.lower(myarr)  #transform into lowercase

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [7]:
np.char.title(myarr)  #transform into title case

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

**6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

In [13]:
import numpy as np
words_arr =np.array(['python','numpy','pandas'])
words_arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [14]:
space_words= np.char.join(" ",words_arr)
space_words

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

**7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [15]:
array1 = np.random.randint(1,5,(3,3)) #creating 2D first array
array1

array([[2, 4, 2],
       [1, 2, 2],
       [4, 4, 2]])

In [16]:
array2 = np.random.randint(6,10,(3,3)) #creating 2D second array
array2

array([[6, 6, 7],
       [9, 8, 7],
       [6, 7, 6]])

In [17]:
array1 + array2 #element addition

array([[ 8, 10,  9],
       [10, 10,  9],
       [10, 11,  8]])

In [18]:
array1 - array2 #subtraction

array([[-4, -2, -5],
       [-8, -6, -5],
       [-2, -3, -4]])

In [19]:
array1 * array2 #multiplication

array([[12, 24, 14],
       [ 9, 16, 14],
       [24, 28, 12]])

In [20]:
array1 / array2 #division

array([[0.33333333, 0.66666667, 0.28571429],
       [0.11111111, 0.25      , 0.28571429],
       [0.66666667, 0.57142857, 0.33333333]])

**8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements**

In [24]:
identity_matrix = np.eye(5,dtype=int)
identity_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [25]:
np.diag(identity_matrix)

array([1, 1, 1, 1, 1])

**9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.**

In [6]:
import numpy as np
myarr = np.random.randint(1,1000,size=100) #creating 100 random integers between 1 to 1000
print("\nRandom integers")
print(myarr)

#function for prime checking
def is_prime(n):
    if n<=1:
        return False
    for i in range(2,int(np.sqrt(n)+1)):
        if n%i == 0:
            return False

    return True
prime_numbers = np.array([i for i in myarr if is_prime(i)]) #calling and iterates the function
print("\nPrime Numbers:")
print(prime_numbers)



Random integers
[640  80  33 409 244 682  19  26 137   4 994 674 641  30 949 970 802 101
   2 157 782 178 179 744 706 993 125 713 189 371 262 552 987 612 737 343
  37 378 404 854 776 373 481 156 195 722 952 565 342 752 836 422 544 758
 802 127 106 446 263 873 343 311 381 323  68 309 598 195 651 754 631 698
 993 265 451 383 215 791 941 892 989 290 377 419 745 209 166 753 700 490
 968 355 883 181 383 455 630 903 533 115]

Prime Numbers:
[409  19 137 641 101   2 157 179  37 373 127 263 311 631 383 941 419 883
 181 383]


**10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.**

In [23]:
daily_temp = np.random.uniform(30,40,30)
print("Daily temperature for a month: ")
print(daily_temp)
weekly_average = [np.mean(daily_temp[i:i+7]) for i in range(0,len(daily_temp),7)]

print("\nWeekly average: ")
for i,avg in enumerate(weekly_average,1):
  print(f'week {i}: {avg:.2f} degrees celcius')

Daily temperature for a month: 
[36.25530404 36.08919069 37.71824698 38.37238101 35.90013432 39.07616852
 39.14563715 36.53567559 38.7168479  31.13674287 37.99727973 31.37789228
 35.15633641 37.66883341 32.47860165 36.31548065 37.85491806 30.46648392
 39.19869467 36.14449733 36.74662631 34.55069795 31.38284764 38.84618255
 34.78924298 32.6885264  30.92882761 30.54715472 36.39108444 31.95941693]

Weekly average: 
week 1: 37.51 degrees celcius
week 2: 35.51 degrees celcius
week 3: 35.60 degrees celcius
week 4: 33.39 degrees celcius
week 5: 34.18 degrees celcius
